import type {
  AiMessage,
  AiSuggestion,
  AppNotification,
  ConnectedAccount,
  Contact,
  Conversation,
  Message,
  StoredFile,
} from './types';

const now = Date.now();
const min = 60_000;
const hr = 3_600_000;
const day = 86_400_000;
const iso = (offset: number) => new Date(now - offset).toISOString();

export const AVATAR_COLORS = [
  '#6366F1',
  '#A855F7',
  '#38BDF8',
  '#22C55E',
  '#F59E0B',
  '#EF4444',
  '#EC4899',
  '#14B8A6',
];

export const contacts: Contact[] = [
  {
    id: 'c1',
    name: 'Amara Okafor',
    email: 'amara@northwind.co',
    phone: '+1 415 555 0102',
    company: 'Northwind Studio',
    role: 'Creative Director',
    avatarColor: '#6366F1',
    initials: 'AO',
    tags: ['Client', 'VIP'],
    notes: 'Prefers async updates. Renewal due Q3.',
    favorite: true,
    lastInteraction: iso(12 * min),
  },
  {
    id: 'c2',
    name: 'Daniel Rivera',
    email: 'd.rivera@lumen.io',
    phone: '+1 212 555 0148',
    company: 'Lumen Labs',
    role: 'Head of Product',
    avatarColor: '#A855F7',
    initials: 'DR',
    tags: ['Partner'],
    notes: 'Introduced by Amara. Interested in the API tier.',
    favorite: false,
    lastInteraction: iso(2 * hr),
  },
  {
    id: 'c3',
    name: 'Sofia Bianchi',
    email: 'sofia@atlasgroup.eu',
    company: 'Atlas Group',
    role: 'COO',
    avatarColor: '#38BDF8',
    initials: 'SB',
    tags: ['Client', 'Enterprise'],
    notes: 'Contract in legal review.',
    favorite: true,
    lastInteraction: iso(5 * hr),
  },
  {
    id: 'c4',
    name: 'Marcus Lee',
    email: 'marcus.lee@brightpath.com',
    phone: '+1 646 555 0199',
    company: 'BrightPath',
    role: 'Founder',
    avatarColor: '#22C55E',
    initials: 'ML',
    tags: ['Lead'],
    notes: 'Cold outreach, warm response.',
    favorite: false,
    lastInteraction: iso(1 * day),
  },
  {
    id: 'c5',
    name: 'Priya Nair',
    email: 'priya@vertex.design',
    company: 'Vertex Design',
    role: 'Design Lead',
    avatarColor: '#F59E0B',
    initials: 'PN',
    tags: ['Vendor'],
    favorite: false,
    lastInteraction: iso(2 * day),
  },
  {
    id: 'c6',
    name: 'Tom Fischer',
    email: 'tom@fischer-legal.de',
    company: 'Fischer Legal',
    role: 'Counsel',
    avatarColor: '#EC4899',
    initials: 'TF',
    tags: ['Legal'],
    favorite: false,
    lastInteraction: iso(3 * day),
  },
];

export const conversations: Conversation[] = [
  {
    id: 'conv1',
    contactId: 'c1',
    channel: 'chat',
    lastPreview: 'Perfect — sending the revised deck now 🎨',
    lastTimestamp: iso(12 * min),
    unread: 2,
    pinned: true,
    encrypted: true,
    muted: false,
  },
  {
    id: 'conv2',
    contactId: 'c3',
    channel: 'email',
    lastPreview: 'Re: Enterprise agreement — redlines attached',
    lastTimestamp: iso(5 * hr),
    unread: 1,
    pinned: true,
    encrypted: false,
    muted: false,
  },
  {
    id: 'conv3',
    contactId: 'c2',
    channel: 'chat',
    lastPreview: 'Can we push the sync to Thursday?',
    lastTimestamp: iso(2 * hr),
    unread: 0,
    pinned: false,
    encrypted: true,
    muted: false,
  },
  {
    id: 'conv4',
    contactId: 'c4',
    channel: 'email',
    lastPreview: 'Thanks for the intro call — following up',
    lastTimestamp: iso(1 * day),
    unread: 0,
    pinned: false,
    encrypted: false,
    muted: false,
  },
  {
    id: 'conv5',
    contactId: 'c5',
    channel: 'chat',
    lastPreview: 'Voice note (0:24)',
    lastTimestamp: iso(2 * day),
    unread: 0,
    pinned: false,
    encrypted: true,
    muted: true,
  },
  {
    id: 'conv6',
    contactId: 'c6',
    channel: 'email',
    lastPreview: 'NDA signed and returned',
    lastTimestamp: iso(3 * day),
    unread: 0,
    pinned: false,
    encrypted: false,
    muted: false,
  },
];

export const messagesByConversation: Record<string, Message[]> = {
  conv1: [
    {
      id: 'm1',
      conversationId: 'conv1',
      kind: 'chat',
      fromMe: false,
      authorId: 'c1',
      body: 'Hey! Did the new brand palette land okay?',
      timestamp: iso(40 * min),
      encrypted: true,
    },
    {
      id: 'm2',
      conversationId: 'conv1',
      kind: 'chat',
      fromMe: true,
      authorId: 'me',
      body: 'It did — the sky accent really pops against the deep navy.',
      timestamp: iso(36 * min),
      status: 'read',
      encrypted: true,
    },
    {
      id: 'm3',
      conversationId: 'conv1',
      kind: 'event',
      fromMe: false,
      authorId: 'system',
      body: 'Amara shared a file',
      timestamp: iso(30 * min),
    },
    {
      id: 'm4',
      conversationId: 'conv1',
      kind: 'attachment',
      fromMe: false,
      authorId: 'c1',
      body: 'Relay_Brand_v3.pdf',
      timestamp: iso(29 * min),
      encrypted: true,
      attachments: [{ id: 'a1', name: 'Relay_Brand_v3.pdf', size: '4.2 MB', kind: 'pdf' }],
    },
    {
      id: 'm5',
      conversationId: 'conv1',
      kind: 'chat',
      fromMe: false,
      authorId: 'c1',
      body: 'Perfect — sending the revised deck now 🎨',
      timestamp: iso(12 * min),
      encrypted: true,
    },
  ],
  conv2: [
    {
      id: 'm6',
      conversationId: 'conv2',
      kind: 'email',
      fromMe: false,
      authorId: 'c3',
      subject: 'Enterprise agreement — redlines attached',
      body: 'Hi,\n\nOur legal team reviewed the draft. A few redlines around data residency and the SLA credits — see the attached document.\n\nCan we schedule 30 minutes this week to walk through them?\n\nBest,\nSofia',
      timestamp: iso(5 * hr),
      attachments: [{ id: 'a2', name: 'MSA_redlines.pdf', size: '812 KB', kind: 'pdf' }],
    },
    {
      id: 'm7',
      conversationId: 'conv2',
      kind: 'email',
      fromMe: true,
      authorId: 'me',
      subject: 'Re: Enterprise agreement',
      body: 'Hi Sofia,\n\nThanks for the fast turnaround. Data residency is fine on our side. Let me confirm the SLA credit structure with finance and revert by tomorrow.\n\nThursday 2pm works for the call.\n\nBest',
      timestamp: iso(4 * hr),
      status: 'delivered',
    },
  ],
  conv3: [
    {
      id: 'm8',
      conversationId: 'conv3',
      kind: 'chat',
      fromMe: false,
      authorId: 'c2',
      body: 'Can we push the sync to Thursday?',
      timestamp: iso(2 * hr),
      encrypted: true,
    },
    {
      id: 'm9',
      conversationId: 'conv3',
      kind: 'chat',
      fromMe: true,
      authorId: 'me',
      body: 'Works for me. 3pm?',
      timestamp: iso(118 * min),
      status: 'read',
      encrypted: true,
    },
  ],
  conv5: [
    {
      id: 'm10',
      conversationId: 'conv5',
      kind: 'voice',
      fromMe: false,
      authorId: 'c5',
      body: 'Voice note',
      timestamp: iso(2 * day),
      durationSec: 24,
      encrypted: true,
    },
  ],
};

export const files: StoredFile[] = [
  {
    id: 'f1',
    name: 'Contracts',
    kind: 'folder',
    size: '12 items',
    owner: 'You',
    modified: iso(1 * day),
    shared: true,
    versions: 1,
  },
  {
    id: 'f2',
    name: 'Brand Assets',
    kind: 'folder',
    size: '48 items',
    owner: 'You',
    modified: iso(3 * hr),
    shared: false,
    versions: 1,
  },
  {
    id: 'f3',
    name: 'Relay_Brand_v3.pdf',
    kind: 'pdf',
    size: '4.2 MB',
    owner: 'Amara Okafor',
    modified: iso(29 * min),
    shared: true,
    versions: 3,
  },
  {
    id: 'f4',
    name: 'MSA_redlines.pdf',
    kind: 'pdf',
    size: '812 KB',
    owner: 'Sofia Bianchi',
    modified: iso(5 * hr),
    shared: true,
    versions: 2,
  },
  {
    id: 'f5',
    name: 'Q3_forecast.xlsx',
    kind: 'sheet',
    size: '1.1 MB',
    owner: 'You',
    modified: iso(1 * day),
    shared: false,
    versions: 5,
  },
  {
    id: 'f6',
    name: 'Hero_mockup.png',
    kind: 'image',
    size: '2.8 MB',
    owner: 'Priya Nair',
    modified: iso(2 * day),
    shared: true,
    versions: 1,
  },
  {
    id: 'f7',
    name: 'Meeting_notes.docx',
    kind: 'doc',
    size: '96 KB',
    owner: 'You',
    modified: iso(6 * hr),
    shared: false,
    versions: 4,
  },
  {
    id: 'f8',
    name: 'Launch_assets.zip',
    kind: 'zip',
    size: '38 MB',
    owner: 'You',
    modified: iso(2 * day),
    shared: false,
    versions: 1,
  },
];

export const aiSuggestions: AiSuggestion[] = [
  {
    id: 's1',
    type: 'summary',
    title: 'Summarize inbox',
    detail: 'Get the highlights of your 6 active threads.',
  },
  {
    id: 's2',
    type: 'draft',
    title: 'Draft a follow-up',
    detail: 'Write a warm follow-up to Marcus Lee.',
  },
  {
    id: 's3',
    type: 'tasks',
    title: 'Extract tasks',
    detail: 'Pull action items from the Atlas thread.',
  },
  {
    id: 's4',
    type: 'reply',
    title: 'Suggest replies',
    detail: 'Quick responses for Sofia’s redlines email.',
  },
];

export const aiSeedMessages: AiMessage[] = [
  {
    id: 'ai1',
    role: 'assistant',
    body: "Hi, I'm your Relay copilot. I can summarize threads, draft emails, rewrite messages, extract tasks, and prep meeting notes. What should we tackle first?",
    timestamp: iso(1 * min),
  },
];

export const notifications: AppNotification[] = [
  {
    id: 'n1',
    type: 'message',
    title: 'Amara Okafor',
    body: 'Perfect — sending the revised deck now',
    timestamp: iso(12 * min),
    read: false,
  },
  {
    id: 'n2',
    type: 'email',
    title: 'Sofia Bianchi',
    body: 'Enterprise agreement — redlines attached',
    timestamp: iso(5 * hr),
    read: false,
  },
  {
    id: 'n3',
    type: 'task',
    title: 'Task due today',
    body: 'Confirm SLA credits with finance',
    timestamp: iso(3 * hr),
    read: false,
  },
  {
    id: 'n4',
    type: 'calendar',
    title: 'Meeting in 30 min',
    body: 'Sync with Daniel Rivera',
    timestamp: iso(30 * min),
    read: true,
  },
  {
    id: 'n5',
    type: 'message',
    title: 'Priya Nair',
    body: 'Voice note (0:24)',
    timestamp: iso(2 * day),
    read: true,
  },
];

export const connectedAccounts: ConnectedAccount[] = [
  { id: 'acc1', provider: 'gmail', email: 'you@gmail.com', status: 'connected' },
  { id: 'acc2', provider: 'outlook', email: 'you@company.com', status: 'connected' },
];

export const currentUser = {
  id: 'me',
  name: 'Jordan Avery',
  email: 'jordan@relay.app',
  initials: 'JA',
  avatarColor: '#6366F1',
  plan: 'Relay Pro',
};

export function getContact(id: string): Contact | undefined {
  return contacts.find((c) => c.id === id);
}
